name: Release

on:
  push:
    branches:
      - main
      - release/**

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
#      - uses: alexandremahdhaoui/github-actions@v0
      - uses: ./.github/actions/semantic-release
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
